### PR TITLE
Reformatted all code and rewrote LaunchpadManager.cs

### PR DESCRIPTION
**Pull request by ExoticGamerrrYT**
Apart from reformatting all the code with [CSharpier](https://csharpier.com/), I have changed the way Stand Launchpad is downloaded, now instead of downloading a `.zip` we use the free [GitHub API](https://docs.github.com/en/rest?apiVersion=2022-11-28) to always download the latest version of the Launchpad ([from its official repo](https://github.com/calamity-inc/Stand-Launchpad)), and we don't download it in a folder, we directly add it to the user's desktop but not before having added that `.exe` to the Windows Defender exclusions 😄.

### CODE REVIEW

**Comment by ExoticGamerrrYT** [comment]
Btw, to format with CSharpier: `dotnet csharpier .` (in the terminal).

**Comment by ExoticGamerrrYT** [comment]
Oh, and I don't want to make another pull request, but I think you have to update the `version.txt` file, don't you?

**Comment by alessandromrc** [comment]
What is the point of this? If you wanted to reformat the code you could have just asked in an issue, also, I don't see formatting being needed at all... ?

Also why are you looking for private information about the contributors of this repo?
It really makes you look bad, you already asked @AXOca for their discord profile and they didn't reply bcs they clearly didn't want to give it to you, but you still continued to ask around.

It is fine to ask for enhancements and also help with the project but doing the things you have done as of now do not put you in a good position at all.

Also never make PRs like this, they would never ever get accepted by anyone, nobody would check what you'd have changed between the files.

**Comment by ExoticGamerrrYT** [comment]
I sincerely apologize for the impression that my actions gave off. I've made some blunders, but my intention was never to cross borders or cause discomfort to anyone. When I requested information and made adjustment suggestions, I ought to have done it with greater consideration and decency. I promise to be more careful from now on and refrain from sending out these kinds of requests for information or queries until I'm sure of the consequences. I thank you for your understanding and apologies once more for the inconvenience. Peace out.

**Pull request closed without merging**
